# syntax=docker/dockerfile:1


FROM apache/couchdb

ENV TZ=CET


COPY docker/local.ini /opt/couchdb/etc/local.ini

RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/CET /etc/localtime

RUN --mount=type=secret,id=couchdb_pw \
	echo "dbadmin = $(cat /run/secrets/couchdb_pw)" >> /opt/couchdb/etc/local.ini

RUN --mount=type=secret,id=couchdb_pw \
	export DBADMIN = $(cat /run/secrets/couchdb_pw)