# syntax=docker/dockerfile:1

# build with: "docker build -t "couchdb-image:latest" -f Dockerfile.couchdb --build-arg pw=PW ."


FROM apache/couchdb

ARG pw

ENV TZ=CET
ENV PW $pw

COPY docker/local.ini /opt/couchdb/etc/local.ini

RUN rm -rf /etc/localtime && ln -s /usr/share/zoneinfo/CET /etc/localtime

RUN echo "dbadmin = $PW" >> /opt/couchdb/etc/local.ini
